# Generated by Django 3.1.7 on 2021-03-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.purchase'),
        ),
    ]
