# Generated by Django 3.1.7 on 2021-03-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_debt_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
    ]
